//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbiturientType
    {
        public AbiturientType()
        {
            this.Person = new HashSet<Person>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> Multiplier { get; set; }
        public Nullable<int> AppSecondTypeId { get; set; }
    
        public virtual ICollection<Person> Person { get; set; }
    }
}
