//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Entry
    {
        public C_Entry()
        {
            this.Application = new HashSet<PriemApplication>();
        }
    
        public System.Guid Id { get; set; }
        public int SemesterId { get; set; }
        public Nullable<System.Guid> StudyPlanId { get; set; }
        public string StudyPlanNumber { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public int LicenseProgramId { get; set; }
        public int ObrazProgramId { get; set; }
        public int ProfileId { get; set; }
        public int StudyBasisId { get; set; }
        public int StudyFormId { get; set; }
        public int StudyLevelId { get; set; }
        public bool IsSecond { get; set; }
        public bool IsReduced { get; set; }
        public bool IsParallel { get; set; }
        public bool IsExpress { get; set; }
        public bool IsElectronic { get; set; }
        public bool IsDistance { get; set; }
        public int CampaignYear { get; set; }
        public Nullable<int> QualificationId { get; set; }
        public Nullable<int> ProgramModeId { get; set; }
        public Nullable<System.DateTime> DateOfClose { get; set; }
        public Nullable<System.DateTime> DateOfStart { get; set; }
        public Nullable<System.DateTime> DateOfClose_Foreign { get; set; }
        public Nullable<System.DateTime> DateOfStart_Foreign { get; set; }
        public Nullable<System.DateTime> DateOfClose_GosLine { get; set; }
        public Nullable<System.DateTime> DateOfStart_GosLine { get; set; }
        public bool IsUsedForPriem { get; set; }
        public Nullable<int> ComissionId { get; set; }
        public bool IsForeign { get; set; }
        public bool IsCrimea { get; set; }
    
        public virtual Semester Semester { get; set; }
        public virtual StudyBasis StudyBasis { get; set; }
        public virtual StudyForm StudyForm { get; set; }
        public virtual ICollection<PriemApplication> Application { get; set; }
        public virtual SP_Faculty_ SP_Faculty { get; set; }
        public virtual SP_LicenseProgram SP_LicenseProgram { get; set; }
        public virtual SP_ObrazProgram SP_ObrazProgram { get; set; }
        public virtual SP_StudyLevel SP_StudyLevel { get; set; }
        public virtual SP_Profile SP_Profile { get; set; }
    }
}
