//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Application = new HashSet<PriemApplication>();
            this.PersonScienceWork = new HashSet<PersonScienceWork>();
            this.PersonEducationDocument = new HashSet<PersonEducationDocument>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public int Barcode { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string SecondName { get; set; }
        public bool Sex { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public Nullable<int> PassportTypeId { get; set; }
        public string PassportSeries { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> PassportDate { get; set; }
        public string PassportAuthor { get; set; }
        public string PassportCode { get; set; }
        public Nullable<System.DateTime> PassportValid { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public int RegistrationStage { get; set; }
        public int AbiturientTypeId { get; set; }
        public bool IsLocked { get; set; }
        public bool IsImported { get; set; }
        public Nullable<System.DateTime> DateReviewDocs { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public bool IsCreatedByComission { get; set; }
        public string SNILS { get; set; }
        public bool HasRussianNationality { get; set; }
    
        public virtual ICollection<PriemApplication> Application { get; set; }
        public virtual Country Nationality { get; set; }
        public virtual PassportType PassportType { get; set; }
        public virtual PersonAddInfo PersonAddInfo { get; set; }
        public virtual PersonChangeStudyFormReason PersonChangeStudyFormReason { get; set; }
        public virtual PersonContacts PersonContacts { get; set; }
        public virtual PersonDisorderInfo PersonDisorderInfo { get; set; }
        public virtual PersonSchoolInfo PersonSchoolInfo { get; set; }
        public virtual ICollection<PersonScienceWork> PersonScienceWork { get; set; }
        public virtual PersonSportQualification PersonSportQualification { get; set; }
        public virtual PersonVisaInfo PersonVisaInfo { get; set; }
        public virtual ICollection<PersonEducationDocument> PersonEducationDocument { get; set; }
        public virtual PersonCurrentEducation PersonCurrentEducation { get; set; }
        public virtual User User { get; set; }
    }
}
