//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonVisaInfo
    {
        public System.Guid PersonId { get; set; }
        public int CountryId { get; set; }
        public string Town { get; set; }
        public string PostAddress { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Person Person { get; set; }
    }
}
