//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonChangeStudyFormReason
    {
        public System.Guid PersonId { get; set; }
        public string Reason { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
        public Nullable<System.Guid> CommitId { get; set; }
    
        public virtual PriemApplication Application { get; set; }
        public virtual ApplicationCommit ApplicationCommit { get; set; }
        public virtual Person Person { get; set; }
    }
}
