//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonHighEducationInfo
    {
        public int EducationDocumentId { get; set; }
        public Nullable<int> EntryYear { get; set; }
        public int ExitYear { get; set; }
        public string DiplomaTheme { get; set; }
        public int QualificationId { get; set; }
        public int StudyFormId { get; set; }
        public string ProgramName { get; set; }
    
        public virtual Qualification Qualification { get; set; }
        public virtual StudyForm StudyForm { get; set; }
        public virtual PersonEducationDocument PersonEducationDocument { get; set; }
    }
}
