//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonSportQualification
    {
        public System.Guid PersonId { get; set; }
        public int SportQualificationId { get; set; }
        public string SportQualificationLevel { get; set; }
        public string OtherSportQualification { get; set; }
    
        public virtual SportQualification SportQualification { get; set; }
        public virtual Person Person { get; set; }
    }
}
