//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonChangeStudyFormReason
    {
        public System.Guid PersonId { get; set; }
        public string Reason { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
        public Nullable<System.Guid> CommitId { get; set; }
    
        public virtual PriemApplication Application { get; set; }
        public virtual ApplicationCommit ApplicationCommit { get; set; }
        public virtual Person Person { get; set; }
    }
}
