//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonAddInfo
    {
        public System.Guid PersonId { get; set; }
        public string MaritalStatus { get; set; }
        public string SocialStatus { get; set; }
        public string AddInfo { get; set; }
        public string Parents { get; set; }
        public Nullable<bool> HasPrivileges { get; set; }
        public Nullable<bool> HostelAbit { get; set; }
        public Nullable<int> ReturnDocumentTypeId { get; set; }
        public bool HostelEduc { get; set; }
        public bool HasTRKI { get; set; }
        public string TRKICertificateNumber { get; set; }
        public bool StartEnglish { get; set; }
        public double EnglishMark { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public string Parent_Surname { get; set; }
        public string Parent_Name { get; set; }
        public string Parent_SecondName { get; set; }
        public string Parent_Phone { get; set; }
        public string Parent_Email { get; set; }
        public string Parent_Work { get; set; }
        public string Parent_WorkPosition { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
