//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonDisorderInfo
    {
        public System.Guid PersonId { get; set; }
        public string YearOfDisorder { get; set; }
        public string EducationProgramName { get; set; }
        public bool IsForIGA { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
