//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonAddInfo
    {
        public System.Guid PersonId { get; set; }
        public string MaritalStatus { get; set; }
        public string SocialStatus { get; set; }
        public string AddInfo { get; set; }
        public string Parents { get; set; }
        public Nullable<bool> HasPrivileges { get; set; }
        public Nullable<bool> HostelAbit { get; set; }
        public Nullable<int> ReturnDocumentTypeId { get; set; }
        public bool HostelEduc { get; set; }
        public bool HasTRKI { get; set; }
        public string TRKICertificateNumber { get; set; }
        public bool StartEnglish { get; set; }
        public double EnglishMark { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public string Parent_Surname { get; set; }
        public string Parent_Name { get; set; }
        public string Parent_SecondName { get; set; }
        public string Parent_Phone { get; set; }
        public string Parent_Email { get; set; }
        public string Parent_Work { get; set; }
        public string Parent_WorkPosition { get; set; }
        public string Parent2_Surname { get; set; }
        public string Parent2_Name { get; set; }
        public string Parent2_SecondName { get; set; }
        public string Parent2_Phone { get; set; }
        public string Parent2_Email { get; set; }
        public string Parent2_Work { get; set; }
        public string Parent2_WorkPosition { get; set; }
        public bool NeedSpecialConditions { get; set; }
        public string UserAD { get; set; }
        public Nullable<bool> PassExamInSpbu { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
