//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.PersonContacts = new HashSet<PersonContacts>();
            this.Country = new HashSet<Country>();
            this.PersonEducationDocument = new HashSet<PersonEducationDocument>();
            this.PersonCurrentEducation = new HashSet<PersonCurrentEducation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<int> RegionNumber { get; set; }
        public string RodName { get; set; }
        public int PriemDictionaryId { get; set; }
        public string KladrCode { get; set; }
        public string RegionNumberStringValue { get; set; }
    
        public virtual ICollection<PersonContacts> PersonContacts { get; set; }
        public virtual ICollection<Country> Country { get; set; }
        public virtual ICollection<PersonEducationDocument> PersonEducationDocument { get; set; }
        public virtual ICollection<PersonCurrentEducation> PersonCurrentEducation { get; set; }
    }
}
