//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_LicenseProgram
    {
        public SP_LicenseProgram()
        {
            this.SP_ObrazProgram = new HashSet<SP_ObrazProgram>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public string Acronym { get; set; }
        public string Code { get; set; }
        public int LicenseId { get; set; }
        public int StudyLevelId { get; set; }
        public int ProgramTypeId { get; set; }
        public string ApplicationNum { get; set; }
        public string PositionNum { get; set; }
        public string PartNum { get; set; }
        public string NormativePeriod { get; set; }
        public string NormativePeriodEng { get; set; }
        public Nullable<int> QualificationId { get; set; }
        public int AggregateGroupId { get; set; }
        public bool IsOpen { get; set; }
        public string Holder { get; set; }
        public string Author { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual SP_StudyLevel SP_StudyLevel { get; set; }
        public virtual ICollection<SP_ObrazProgram> SP_ObrazProgram { get; set; }
        public virtual SP_Qualification SP_Qualification { get; set; }
    }
}
