//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_ObrazProgram
    {
        public SP_ObrazProgram()
        {
            this.SP_ObrazProgramInYear = new HashSet<SP_ObrazProgramInYear>();
            this.SP_StudyPlan = new HashSet<SP_StudyPlan>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public string Acronym { get; set; }
        public string PrintName { get; set; }
        public string Number { get; set; }
        public int LicenseProgramId { get; set; }
        public int FacultyId { get; set; }
        public string OrderStart { get; set; }
        public string OrderClose { get; set; }
        public Nullable<int> SpecialistId { get; set; }
        public Nullable<int> ProgramStatusId { get; set; }
        public int ProgramModeId { get; set; }
        public string Agreement { get; set; }
        public Nullable<int> MobilityTypeId { get; set; }
        public bool IsExpress { get; set; }
        public bool IsOpen { get; set; }
        public string Holder { get; set; }
        public bool IsUseEng { get; set; }
        public string AdditionalInfo { get; set; }
        public double HoursForCredit { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdate { get; set; }
        public string Author { get; set; }
    
        public virtual SP_Faculty SP_Faculty { get; set; }
        public virtual SP_LicenseProgram SP_LicenseProgram { get; set; }
        public virtual ICollection<SP_ObrazProgramInYear> SP_ObrazProgramInYear { get; set; }
        public virtual ICollection<SP_StudyPlan> SP_StudyPlan { get; set; }
    }
}
