//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_StudyLevel
    {
        public SP_StudyLevel()
        {
            this.SP_LicenseProgram = new HashSet<SP_LicenseProgram>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public string Acronym { get; set; }
        public string Crypt { get; set; }
        public string FurtherStudy { get; set; }
        public string FurtherStudyEng { get; set; }
        public string LevelGroup { get; set; }
        public Nullable<int> StudyLevelGroupId { get; set; }
        public Nullable<int> EducationPermitId { get; set; }
        public Nullable<int> EducationDocumentId { get; set; }
        public bool HasTwoLicenseProgram { get; set; }
        public Nullable<int> StudyPlanPrintFormTypeId { get; set; }
        public bool IsOpen { get; set; }
        public string Holder { get; set; }
        public Nullable<int> StudyPlanIndividualPrintFormTypeId { get; set; }
        public bool IsUseEng { get; set; }
        public bool IsUseForPrint { get; set; }
        public string Author { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual SP_EducationDocument SP_EducationDocument { get; set; }
        public virtual SP_EducationPermit SP_EducationPermit { get; set; }
        public virtual ICollection<SP_LicenseProgram> SP_LicenseProgram { get; set; }
        public virtual SP_StudyLevelGroup SP_StudyLevelGroup { get; set; }
    }
}
