//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_StudyPlan
    {
        public SP_StudyPlan()
        {
            this.SP_ProfileInStudyPlan = new HashSet<SP_ProfileInStudyPlan>();
        }
    
        public System.Guid Id { get; set; }
        public int PlanYearId { get; set; }
        public Nullable<int> PlanNum { get; set; }
        public Nullable<System.DateTime> PlanDate { get; set; }
        public int ObrazProgramId { get; set; }
        public Nullable<int> EducationPeriodId { get; set; }
        public int StudyFormId { get; set; }
        public string ProfileGroupName { get; set; }
        public string ProfileGroupNameEng { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> PayPeriodId { get; set; }
        public Nullable<int> KCPBudget { get; set; }
        public Nullable<int> KCPContract { get; set; }
        public Nullable<int> KCPSecond { get; set; }
        public Nullable<int> KontBudget { get; set; }
        public Nullable<int> KontContract { get; set; }
        public Nullable<int> InoBudget { get; set; }
        public Nullable<int> InoContract { get; set; }
        public string OrderInfo { get; set; }
        public string InfoMedium { get; set; }
        public string InfoIGA { get; set; }
        public string InfoFinish { get; set; }
        public Nullable<System.DateTime> DateFinish { get; set; }
        public Nullable<System.DateTime> DateDiplomaIssue { get; set; }
        public Nullable<int> WorkHours { get; set; }
        public Nullable<double> Credits { get; set; }
        public int StatusId { get; set; }
        public bool RusAsForeign { get; set; }
        public bool IsSeparateProfileEntry { get; set; }
        public bool IsExpress { get; set; }
        public bool IsParallel { get; set; }
        public bool IsReduced { get; set; }
        public bool IsIndividual { get; set; }
        public bool IsElectronic { get; set; }
        public bool IsDistance { get; set; }
        public Nullable<int> KCPForeignBudget { get; set; }
        public Nullable<int> KCPForeignContract { get; set; }
        public bool IsOpen { get; set; }
        public string Holder { get; set; }
        public string PersonFIO { get; set; }
        public Nullable<System.DateTime> PersonBirthDate { get; set; }
        public string PersonSurname { get; set; }
        public string PersonName { get; set; }
        public string PersonSecondName { get; set; }
        public int PlanStartBaseScheduleId { get; set; }
        public int IntId { get; set; }
        public bool HasKontByProfiles { get; set; }
        public bool IsUseEng { get; set; }
        public bool IsUseForPrint { get; set; }
        public System.DateTime DateCreate { get; set; }
        public System.DateTime DateUpdate { get; set; }
        public string Author { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string AdditionalInfo { get; set; }
    
        public virtual SP_EducationPeriod SP_EducationPeriod { get; set; }
        public virtual SP_ObrazProgram SP_ObrazProgram { get; set; }
        public virtual SP_PayPeriod SP_PayPeriod { get; set; }
        public virtual ICollection<SP_ProfileInStudyPlan> SP_ProfileInStudyPlan { get; set; }
        public virtual SP_StudyForm SP_StudyForm { get; set; }
        public virtual SP_Status SP_Status { get; set; }
        public virtual SP_Year SP_Year { get; set; }
    }
}
