//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Person = new HashSet<Person>();
        }
    
        public System.Guid Id { get; set; }
        public bool IsApproved { get; set; }
        public bool IsForeign { get; set; }
        public bool IsDormsAccount { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string SID { get; set; }
        public string EmailTicket { get; set; }
        public string UILanguage { get; set; }
        public System.DateTime RegDate { get; set; }
        public int CampaignYear { get; set; }
        public string Login { get; set; }
        public bool IsAD { get; set; }
    
        public virtual ICollection<Person> Person { get; set; }
    }
}
