//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class extAbitFiles_All
    {
        public System.Guid Id { get; set; }
        public System.Guid PersonId { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
        public Nullable<System.Guid> CommitId { get; set; }
        public string FileName { get; set; }
        public int FileSize { get; set; }
        public string FileExtention { get; set; }
        public byte[] FileData { get; set; }
        public string Comment { get; set; }
        public System.DateTime LoadDate { get; set; }
        public bool IsReadOnly { get; set; }
        public string MimeType { get; set; }
        public bool IsApproved { get; set; }
    }
}
