//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonDisorderInfo
    {
        public System.Guid PersonId { get; set; }
        public string YearOfDisorder { get; set; }
        public string EducationProgramName { get; set; }
        public bool IsForIGA { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
