//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonSchoolInfo
    {
        public System.Guid PersonId { get; set; }
        public int SchoolTypeId { get; set; }
        public int SchoolExitClassId { get; set; }
        public string SchoolAddress { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
