//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semester
    {
        public Semester()
        {
            this.C_Entry = new HashSet<C_Entry>();
            this.PersonCurrentEducation = new HashSet<PersonCurrentEducation>();
        }
    
        public int Id { get; set; }
        public Nullable<int> EducYear { get; set; }
        public string Name { get; set; }
        public bool IsIGA { get; set; }
        public int NextSemesterId { get; set; }
    
        public virtual ICollection<C_Entry> C_Entry { get; set; }
        public virtual ICollection<PersonCurrentEducation> PersonCurrentEducation { get; set; }
    }
}
