//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationCommitVersonDetails
    {
        public int Id { get; set; }
        public int ApplicationCommitVersionId { get; set; }
        public System.Guid ApplicationId { get; set; }
        public int Priority { get; set; }
    }
}
