//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationCommit
    {
        public System.Guid Id { get; set; }
        public int IntNumber { get; set; }
        public bool IsPrinted { get; set; }
        public bool IsImported { get; set; }
        public Nullable<System.DateTime> DateReviewDocs { get; set; }
    }
}
