//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationCommit
    {
        public ApplicationCommit()
        {
            this.PersonChangeStudyFormReason = new HashSet<PersonChangeStudyFormReason>();
        }
    
        public System.Guid Id { get; set; }
        public int IntNumber { get; set; }
        public bool IsPrinted { get; set; }
        public bool IsImported { get; set; }
        public Nullable<System.DateTime> DateReviewDocs { get; set; }
    
        public virtual ICollection<PersonChangeStudyFormReason> PersonChangeStudyFormReason { get; set; }
    }
}
