//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Entry
    {
        public C_Entry()
        {
            this.Application = new HashSet<PriemApplication>();
        }
    
        public System.Guid Id { get; set; }
        public int SemesterId { get; set; }
        public Nullable<System.Guid> StudyPlanId { get; set; }
        public string StudyPlanNumber { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public string FacultyName { get; set; }
        public int LicenseProgramId { get; set; }
        public string LicenseProgramName { get; set; }
        public string LicenseProgramNameEng { get; set; }
        public string LicenseProgramCode { get; set; }
        public int ObrazProgramId { get; set; }
        public string ObrazProgramName { get; set; }
        public string ObrazProgramNameEng { get; set; }
        public string ObrazProgramCrypt { get; set; }
        public string ProfileName { get; set; }
        public string ProfileNameEng { get; set; }
        public int StudyBasisId { get; set; }
        public string StudyBasisName { get; set; }
        public string StudyBasisNameEng { get; set; }
        public string StudyBasisAcronym { get; set; }
        public int StudyFormId { get; set; }
        public string StudyFormName { get; set; }
        public string StudyFormNameEng { get; set; }
        public int StudyLevelId { get; set; }
        public string StudyLevelName { get; set; }
        public Nullable<System.Guid> SeparateEntryProfileInSPId { get; set; }
        public Nullable<System.Guid> ProfileId { get; set; }
        public bool IsSecond { get; set; }
        public bool IsReduced { get; set; }
        public bool IsParallel { get; set; }
        public bool IsExpress { get; set; }
        public bool IsElectronic { get; set; }
        public bool IsDistance { get; set; }
        public Nullable<int> CampaignYear { get; set; }
        public Nullable<int> QualificationId { get; set; }
        public string QualificationName { get; set; }
        public Nullable<int> AggregateGroupId { get; set; }
        public string AggregateGroupName { get; set; }
        public Nullable<int> ProgramModeId { get; set; }
        public string ProgramModeName { get; set; }
        public Nullable<int> EducationPeriodId { get; set; }
        public string EducationPeriodName { get; set; }
        public Nullable<System.DateTime> DateOfClose { get; set; }
        public Nullable<System.DateTime> DateOfStart { get; set; }
        public Nullable<System.DateTime> DateOfClose_Foreign { get; set; }
        public Nullable<System.DateTime> DateOfStart_Foreign { get; set; }
        public Nullable<System.DateTime> DateOfClose_GosLine { get; set; }
        public Nullable<System.DateTime> DateOfStart_GosLine { get; set; }
        public bool IsUsedForPriem { get; set; }
        public Nullable<int> ComissionId { get; set; }
    
        public virtual ICollection<PriemApplication> Application { get; set; }
        public virtual Semester Semester { get; set; }
    }
}
