//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Person = new HashSet<Person>();
            this.PersonContacts = new HashSet<PersonContacts>();
            this.PersonEducationDocument = new HashSet<PersonEducationDocument>();
        }
    
        public int Id { get; set; }
        public string NameEng { get; set; }
        public string Name { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> LevelOfUsing { get; set; }
        public Nullable<int> PriemDictionaryId { get; set; }
        public bool IsCountry { get; set; }
        public bool IsNationality { get; set; }
        public bool IsSNG { get; set; }
        public bool IsRussia { get; set; }
    
        public virtual ICollection<Person> Person { get; set; }
        public virtual ICollection<PersonContacts> PersonContacts { get; set; }
        public virtual ICollection<PersonEducationDocument> PersonEducationDocument { get; set; }
    }
}
