//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class extStudyPlan
    {
        public System.Guid Id { get; set; }
        public string StudyPlanNumber { get; set; }
        public Nullable<int> PlanYearId { get; set; }
        public string PlanYear { get; set; }
        public Nullable<int> PlanNum { get; set; }
        public Nullable<System.DateTime> PlanDate { get; set; }
        public Nullable<int> ObrazProgramId { get; set; }
        public Nullable<int> EducationPeriodId { get; set; }
        public Nullable<int> StudyFormId { get; set; }
        public string ProfileGroupName { get; set; }
        public string ProfileGroupNameEng { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> PayPeriodId { get; set; }
        public Nullable<int> KCPBudget { get; set; }
        public Nullable<int> KCPContract { get; set; }
        public Nullable<int> KontBudget { get; set; }
        public Nullable<int> KontContract { get; set; }
        public Nullable<int> InoBudget { get; set; }
        public Nullable<int> InoContract { get; set; }
        public string OrderInfo { get; set; }
        public string InfoMedium { get; set; }
        public string InfoIGA { get; set; }
        public string InfoFinish { get; set; }
        public Nullable<System.DateTime> DateFinish { get; set; }
        public Nullable<System.DateTime> DateDiplomaIssue { get; set; }
        public Nullable<int> WorkHours { get; set; }
        public Nullable<double> Credits { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string ObrazProgramName { get; set; }
        public string ObrazProgramNumber { get; set; }
        public Nullable<int> LicenseProgramId { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public Nullable<int> ProgramStatusId { get; set; }
        public Nullable<int> ProgramModeId { get; set; }
        public string FacultyName { get; set; }
        public string FacultyCode { get; set; }
        public string EducationPeriodName { get; set; }
        public string LicenseProgramName { get; set; }
        public string LicenseProgramShortName { get; set; }
        public string LicenseProgramCode { get; set; }
        public Nullable<int> LicenseId { get; set; }
        public Nullable<int> StudyLevelId { get; set; }
        public Nullable<int> ProgramTypeId { get; set; }
        public Nullable<int> QualificationId { get; set; }
        public string ProgramModeName { get; set; }
        public string ProgramModeShortName { get; set; }
        public string ProgramTypeName { get; set; }
        public string PayPeriodName { get; set; }
        public string ProgramStatusName { get; set; }
        public string QualificationName { get; set; }
        public string QualificationShortName { get; set; }
        public string YearName { get; set; }
        public string QualificationCode { get; set; }
        public string StudyLevelName { get; set; }
        public string StudyLevelShortName { get; set; }
        public string StudyLevelCrypt { get; set; }
        public string StatusName { get; set; }
        public string StudyFormName { get; set; }
        public string ObrazProgramCrypt { get; set; }
        public string ProgramModeAcronym { get; set; }
        public string StudyLevelAcronym { get; set; }
        public bool RusAsForeign { get; set; }
        public string RusAsForeignPrintName { get; set; }
        public bool IsSeparateProfileEntry { get; set; }
        public Nullable<System.Guid> ObrazProgramInYearId { get; set; }
        public string ObrazProgramNameEng { get; set; }
        public string FacultyNameEng { get; set; }
        public string LicenseProgramNameEng { get; set; }
        public string ProgramModeNameEng { get; set; }
        public string ProgramTypeNameEng { get; set; }
        public string StudyFormNameEng { get; set; }
        public string StudyLevelNameEng { get; set; }
        public Nullable<int> KCPSecond { get; set; }
        public bool IsExpress { get; set; }
        public bool IsParallel { get; set; }
        public bool IsReduced { get; set; }
        public bool IsIndividual { get; set; }
        public Nullable<System.DateTime> PersonBirthDate { get; set; }
        public bool IsElectronic { get; set; }
        public bool IsDistance { get; set; }
        public Nullable<int> KCPForeignBudget { get; set; }
        public Nullable<int> KCPForeignContract { get; set; }
        public Nullable<int> AggregateGroupId { get; set; }
        public string AggregateGroupName { get; set; }
        public string AggregateGroupAcr { get; set; }
        public string PersonSurname { get; set; }
        public string PersonName { get; set; }
        public string PersonSecondName { get; set; }
        public int IntId { get; set; }
        public Nullable<int> ObrazProgramInYearIntId { get; set; }
    }
}
