//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonHighEducationInfo
    {
        public System.Guid PersonId { get; set; }
        public Nullable<int> EntryYear { get; set; }
        public Nullable<int> ExitYear { get; set; }
        public string DiplomaTheme { get; set; }
        public Nullable<int> QualificationId { get; set; }
        public Nullable<int> StudyFormId { get; set; }
        public string ProgramName { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Qualification Qualification { get; set; }
        public virtual Qualification Qualification1 { get; set; }
        public virtual StudyForm StudyForm { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
