//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonEducationDocument
    {
        public System.Guid PersonId { get; set; }
        public Nullable<int> SchoolTypeId { get; set; }
        public Nullable<int> CountryEducId { get; set; }
        public string SchoolCity { get; set; }
        public string SchoolName { get; set; }
        public string SchoolNum { get; set; }
        public string SchoolExitYear { get; set; }
        public string Series { get; set; }
        public string Number { get; set; }
        public Nullable<bool> IsEqual { get; set; }
        public string EqualDocumentNumber { get; set; }
        public string AttestatRegion { get; set; }
        public string AttestatSeries { get; set; }
        public string AttestatNumber { get; set; }
        public Nullable<double> AvgMark { get; set; }
        public Nullable<bool> IsExcellent { get; set; }
        public Nullable<bool> StartEnglish { get; set; }
        public Nullable<double> EnglishMark { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<bool> HasTRKI { get; set; }
        public string TRKICertificateNumber { get; set; }
        public Nullable<int> RegionEducId { get; set; }
        public Nullable<int> VuzAdditionalTypeId { get; set; }
        public Nullable<int> SchoolExitClassId { get; set; }
    
        public virtual Country CountryEduc { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual Region Region { get; set; }
    }
}
