//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonEducationDocument
    {
        public int Id { get; set; }
        public System.Guid PersonId { get; set; }
        public int SchoolTypeId { get; set; }
        public int CountryEducId { get; set; }
        public int RegionEducId { get; set; }
        public Nullable<int> VuzAdditionalTypeId { get; set; }
        public string SchoolCity { get; set; }
        public string SchoolName { get; set; }
        public string SchoolNum { get; set; }
        public string SchoolExitYear { get; set; }
        public Nullable<int> SchoolExitClassId { get; set; }
        public string Series { get; set; }
        public string Number { get; set; }
        public bool IsEqual { get; set; }
        public string EqualDocumentNumber { get; set; }
        public Nullable<double> AvgMark { get; set; }
        public bool IsExcellent { get; set; }
    
        public virtual Country CountryEduc { get; set; }
        public virtual Person Person { get; set; }
        public virtual Region RegionEduc { get; set; }
        public virtual PersonHighEducationInfo PersonHighEducationInfo { get; set; }
    }
}
