//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonCurrentEducation
    {
        public System.Guid PersonId { get; set; }
        public Nullable<int> EducTypeId { get; set; }
        public Nullable<int> SemesterId { get; set; }
        public Nullable<int> StudyLevelId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<bool> HasScholarship { get; set; }
        public Nullable<bool> HasAccreditation { get; set; }
        public string EducName { get; set; }
        public string AccreditationNumber { get; set; }
        public Nullable<System.DateTime> AccreditationDate { get; set; }
        public Nullable<int> LicenseProgramId { get; set; }
        public string ProfileName { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> StudyFormId { get; set; }
        public Nullable<int> StudyBasisId { get; set; }
        public Nullable<int> ObrazProgramId { get; set; }
        public Nullable<System.Guid> ProfileId { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
