//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonAddInfo
    {
        public System.Guid PersonId { get; set; }
        public string MaritalStatus { get; set; }
        public string SocialStatus { get; set; }
        public string AddInfo { get; set; }
        public string Parents { get; set; }
        public Nullable<bool> HasPrivileges { get; set; }
        public Nullable<bool> HostelAbit { get; set; }
        public Nullable<int> ReturnDocumentTypeId { get; set; }
        public bool HostelEduc { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
