//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.PersonContacts = new HashSet<PersonContacts>();
            this.PersonEducationDocument = new HashSet<PersonEducationDocument>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<int> RegionNumber { get; set; }
        public string RodName { get; set; }
        public Nullable<int> PriemDictionaryId { get; set; }
        public string KladrCode { get; set; }
        public string RegionNumberStringValue { get; set; }
    
        public virtual ICollection<PersonContacts> PersonContacts { get; set; }
        public virtual ICollection<PersonEducationDocument> PersonEducationDocument { get; set; }
    }
}
