//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_Faculty
    {
        public SP_Faculty()
        {
            this.SP_ObrazProgram = new HashSet<SP_ObrazProgram>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public string Acronym { get; set; }
        public string Code { get; set; }
        public string RodName { get; set; }
        public string DatName { get; set; }
        public string Site { get; set; }
        public string Crypt { get; set; }
        public string AcronymEng { get; set; }
        public Nullable<int> ExpertOrder { get; set; }
        public bool IsOpen { get; set; }
        public string Holder { get; set; }
        public bool IsArchive { get; set; }
    
        public virtual ICollection<SP_ObrazProgram> SP_ObrazProgram { get; set; }
    }
}
