//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_Faculty_
    {
        public SP_Faculty_()
        {
            this.C_Entry = new HashSet<C_Entry>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public string Acronym { get; set; }
        public string RodName { get; set; }
        public string DatName { get; set; }
        public string VinName { get; set; }
    
        public virtual ICollection<C_Entry> C_Entry { get; set; }
    }
}
