//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_ObrazProgramInYear
    {
        public System.Guid Id { get; set; }
        public int ObrazProgramId { get; set; }
        public int YearId { get; set; }
        public Nullable<int> StandartId { get; set; }
        public string DescriptionOrder { get; set; }
        public bool MayBeExpress { get; set; }
        public bool MayBeParallel { get; set; }
        public bool MayBeReduced { get; set; }
        public bool MayBeIndividual { get; set; }
        public bool MayBeElectronic { get; set; }
        public bool MayBeDistance { get; set; }
        public string ScienceDirector { get; set; }
        public bool IsOpen { get; set; }
        public string Holder { get; set; }
        public int IntId { get; set; }
    
        public virtual SP_ObrazProgram SP_ObrazProgram { get; set; }
        public virtual SP_Year SP_Year { get; set; }
    }
}
