//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_ProfileInStudyPlan
    {
        public System.Guid Id { get; set; }
        public System.Guid StudyPlanId { get; set; }
        public int ProfileId { get; set; }
        public int IntId { get; set; }
        public string Author { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual SP_Profile SP_Profile { get; set; }
        public virtual SP_StudyPlan SP_StudyPlan { get; set; }
    }
}
