//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemForeignInspector
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid Id { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsForeign { get; set; }
        public Nullable<bool> IsDormsAccount { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string SID { get; set; }
        public string EmailTicket { get; set; }
        public string UILanguage { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public int CampaignYear { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
